'use strict';
const $ = id => document.getElementById(id);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const timeText = t => t ? new Date(typeof t === 'number' ? t * 1000 : t).toLocaleString('zh-CN', {timeZone:'Asia/Shanghai',hour12:false}) : '—';
const navs = ['分析工作台','回测与监控','参数配置','使用指南'];
const stateNames = {pending:'待执行',running:'更新中',success:'已完成',stale:'本轮未更新',error:'失败',stopped:'已停止',interrupted:'已中断',stopping:'停止中',blocked:'前置阻断'};
let modules=[], targets=[], presets=[], state={}, selected=0, tab=0, page=0, toastTimer, resultToken=0, dirty=false, lastResultKey='';
const resultCache=new Map();
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,6000)}
async function api(path,body){const r=await fetch('/api/analysis/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok||d.ok===false)throw Error(d.error||'请求失败');return d}
async function act(fn){try{await fn()}catch(e){toast(e.message)}}
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function applyConfig(){const c=state.cfg||{};$('from').value=c.from||'';$('every').value=c.intervalMinutes||5;$('keep').value=c.keep||10;$('near').value=c.near||1;$('with30s').checked=!!c.with30s;$('mode').value=state.auto?'auto':'manual';$('everyLabel').hidden=!state.auto;if(c.targetId)$('target').value=c.targetId;dirty=false}
async function refreshTargets(){const d=await api('targets');targets=d.targets.filter(t=>!t.error);$('target').innerHTML='<option value="">请选择图表</option>'+targets.map(t=>`<option value="${esc(t.id)}">${esc(t.symbol)}${t.replay?" · 历史回放中":""} · ${esc(t.title||t.id)}</option>`).join('');const saved=state.cfg?.targetId;if(saved&&targets.some(t=>t.id===saved))$('target').value=saved;else if(targets.length===1)$('target').value=targets[0].id;$('connection').textContent=targets.length?'TradingView已连接':'未找到可用图表';if(!targets.length)toast('请打开TradingView图表并启用9222调试端口');updateSymbol()}
function updateSymbol(){const t=targets.find(t=>t.id===$('target').value);$('symbolLabel').textContent=t?.symbol||'尚未选择图表';$('connection').textContent=t?.replay?'历史回放中 · 当前分析暂停':t?'TradingView已连接':'TradingView未选择'}
async function refreshPresets(){const r=await fetch('/api/sr/presets');const d=await r.json();presets=d.presets||[];const sr=state.cfg?.sr;$('preset').innerHTML='<option value="default">WEB默认参数</option>'+(sr?'<option value="saved">当前分析配置</option>':'')+presets.map((p,i)=>`<option value="${i}">${esc(p.name)}</option>`).join('');if(sr)$('preset').value='saved'}
async function save(){const target=targets.find(t=>t.id===$('target').value);if(!target)throw Error('请选择有效目标图表');let sr=$('preset').value==='saved'?state.cfg.sr:$('preset').value==='default'?{srTypes:['cluster','boll']}:presets[Number($('preset').value)]?.cfg;if(!sr)throw Error('预设已失效，请重新选择');const cfg={targetId:target.id,symbol:target.symbol,from:$('from').value,intervalMinutes:Number($('every').value),keep:Number($('keep').value),near:Number($('near').value),with30s:$('with30s').checked,sr};const d=await api('config',{cfg});dirty=false;updateState(d);return d}
function updateState(d){state=d;const job=d.job;const busy=['running','stopping'].includes(job?.state);$('run').disabled=busy;$('single').disabled=busy;$('stop').disabled=!busy&&!d.auto;if(!dirty){$('mode').value=d.auto?'auto':'manual';$('everyLabel').hidden=!d.auto}$('schedule').textContent=d.waiting?d.waiting:busy?`${stateNames[job.state]} · 正在使用目标图表`:d.auto?`自动 · 轮次间隔${d.cfg.intervalMinutes}分钟 · 下次 ${timeText(d.nextAt)}`:'手动模式 · '+(stateNames[job?.state]||'等待执行');$('last').textContent='最近完整成功：'+timeText(d.lastSuccess?.at);$('error').hidden=!job?.error&&!d.resultsStale;$('error').textContent=job?.error||(d.resultsStale?'当前配置已改变，下方结果来自上一配置，请重新更新。':'');$('log').textContent=(job?.logs||[]).join('\n')||'等待开始。';drawFlow();if(tab===0){const key=JSON.stringify([job?.id,job?.state,job?.stages?.[modules[selected]?.id]]);if(key!==lastResultKey){lastResultKey=key;detail()}}}
function drawFlow(){if(!modules.length)return;$('flow').innerHTML=modules.map((m,i)=>{const s=state.job?.stages?.[m.id]?.state;return `<button class="step ${i===selected?'selected':''} ${s==='success'?'done':''} ${s==='running'?'running':''}" data-module="${i}" aria-pressed="${i===selected}"><span class="n">0${i+1}${i<5?'　→':''}</span><strong>${esc(m.name)}</strong><small>${stateNames[s]||'待更新'}</small></button>`}).join('')}
async function detail(){if(!modules.length)return;const token=++resultToken,m=modules[selected];$('moduleTitle').textContent=m.name;$('eyebrow').textContent=`步骤 0${selected+1} / ${m.desc}`;$('tabs').innerHTML=['操作与结果','规则说明','依赖与示例'].map((x,i)=>`<button role="tab" aria-selected="${i===tab}" class="${i===tab?'active':''}" data-tab="${i}">${x}</button>`).join('');
if(tab===1){$('detail').innerHTML=`<div class="rules">${m.rules.map(r=>`<article><h3>${esc(r[0])}</h3><p>${esc(r[1])}</p></article>`).join('')}</div><div class="sources">规则依据：${esc(m.source)}</div><details><summary id="loadDoc">展开原始技能说明</summary><pre id="fullDoc" style="white-space:pre-wrap;font:13px/1.8 inherit"></pre></details>`;$('loadDoc').parentElement.addEventListener('toggle',async e=>{if(!e.target.open||$('fullDoc').textContent)return;try{const d=await api('docs?module='+m.id);if(token===resultToken)$('fullDoc').textContent=(d.note?d.note+'\n\n':'')+d.text}catch(err){toast(err.message)}});return}
if(tab===2){$('detail').innerHTML=`<div class="two"><div class="box"><h3>运行前置</h3><p>${m.deps.length?m.deps.map(i=>`<button class="btn" data-module="${i}">${esc(modules[i].name)}</button>`).join(' '):'TradingView连接正常，选择品种与起始日期。'}</p><p class="muted">单项运行重新计算必要前置，使用同轮笔和选定WEB支阻参数。上游失败即停止后续步骤。</p><h3>输出</h3><p>${esc(m.out)}</p></div><div class="box"><h3>示例</h3><p>${esc(m.example)}</p></div></div><div class="note">单项更新后，其他模块标为本轮未更新；需要全部一致的图表结果请运行“更新全部”。</div>`;return}
const stage=state.job?.stages?.[m.id];$('detail').innerHTML=`<div class="metrics"><div class="metric"><span class="caption">模块状态</span><strong>${stateNames[stage?.state]||'尚未运行'}</strong></div><div class="metric"><span class="caption">完成时间</span><strong style="font-size:15px">${timeText(stage?.finishedAt)}</strong></div><div class="metric"><span class="caption">任务版本</span><strong style="font-size:15px">${esc(state.job?.id?.slice(0,8)||'—')}</strong></div></div><div id="results"><p class="muted">${stage?.state==='success'?'正在读取结果…':'本轮尚无成功结果。请运行本模块或更新全部。'}</p></div>`;
if(stage?.state!=='success')return;try{const cacheKey=state.job.id+':'+m.id;let d=resultCache.get(cacheKey);if(!d){d=await api('result?module='+m.id);if(d.data)resultCache.set(cacheKey,d)}if(token!==resultToken)return;const data=d.data;if(!data){$('results').textContent=d.message||'请查看图表及运行日志';return}let rows=[];if(m.id==='plan'){rows=Object.entries(data.periods||{}).map(([p,v])=>[p,v.direction,v.strategy,v.reason]);$('results').innerHTML=table(['周期','方向','策略','理由'],rows)}else if(m.id==='sr'){rows=(data.merged||[]).map(v=>[v.price,v.level||v.source||'',v.type||v.label||'']);$('results').innerHTML=table(['价位','来源','类型'],rows)}else{rows=Object.entries(data.periods||{}).map(([p,v])=>[p,Array.isArray(v)?v.length:1,timeText(stage.result?.dataEnd?.[p]),timeText(Array.isArray(v)?v.at(-1)?.endTime||v.at(-1)?.time:null)]);$('results').innerHTML=table(['周期','结果数量','K线截止时间','末项时间'],rows)}const raw=document.createElement('details'),sum=document.createElement('summary'),pre=document.createElement('pre');sum.textContent='查看完整结果数据';pre.style.cssText='white-space:pre-wrap;max-height:420px;overflow:auto;font-size:12px';pre.textContent=JSON.stringify(data,null,2);raw.append(sum,pre);$('results').append(raw);if(state.job.state!=='success')$('results').insertAdjacentHTML('afterbegin','<div class="note">本步骤完成，但整轮尚未完整成功；图形可能部分更新。</div>')}catch(e){if(token===resultToken)$('results').textContent=e.message}}
function navigate(i){page=i;$('nav').innerHTML=navs.map((n,j)=>`<button data-page="${j}" class="${i===j?'active':''}">${n}</button>`).join('');$('pageTitle').textContent=navs[i];$('pageDesc').textContent=['从结构识别到进出场，按顺序完成一轮分析。','回测、回放、实时监控及历史信号记录。','保留手动调参、自动调参、预设和Excel导入导出。','从操作路径进入各模块，查看规则和依赖。'][i];$('work').hidden=i!==0;$('other').hidden=i!==3;$('legacy').hidden=![1,2].includes(i);if(i===0){drawFlow();detail()}if(i===1||i===2){const url=i===1?'/modes.html?embed=1':'/sr.html?embed=1';if($('legacy').getAttribute('src')!==url)$('legacy').src=url}if(i===3)$('other').innerHTML=`<section class="panel"><h2>首次使用</h2><p>选择图表与起始日期 → 选择支阻位预设 → 更新全部 → 查看模块结果、规则和依赖 → 按需启用自动更新。</p><div class="row">${modules.map((m,j)=>`<button class="btn" data-rule="${j}">${esc(m.name)}规则</button>`).join('')}</div>${[['自动更新','默认手动，自动间隔默认5分钟，可设1至1440分钟。后端调度，关闭页面仍继续；服务重启后自动关闭。单轮运行期间不重复启动，忙时等待；失败后关闭自动并显示原因。'],['停止任务','停止会关闭自动更新，当前模块结束后不再执行下一模块。单模块超时30分钟会终止，图形可能部分更新。'],['结果一致性','每轮固定品种、日期和参数，使用独立任务缓存。全部请求步骤成功后才发布共享缓存。页面显示任务版本、步骤状态和数据截止时间。'],['修改支阻参数','在参数配置中保存预设，返回工作台刷新预设并选用，下一轮分析会使用这些参数。'],['最新笔画不全','先看K线截止时间和任务错误。新反向走势未成笔时不会强行连线；同向末笔按原算法延伸。'],['口径说明','进出场沿用JS技能规则，回测与实时监控沿用现有Python引擎。两者止损等规则可能不同，查看对应说明，不能混用。']].map(r=>`<details><summary>${r[0]}</summary><p>${r[1]}</p></details>`).join('')}</section>`}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.page!==undefined)navigate(+b.dataset.page);if(b.dataset.module!==undefined){selected=+b.dataset.module;drawFlow();detail()}if(b.dataset.tab!==undefined){tab=+b.dataset.tab;detail()}if(b.dataset.rule!==undefined){selected=+b.dataset.rule;tab=1;navigate(0)}});
for(const id of ['target','from','every','preset','keep','near','with30s'])$(id).addEventListener('change',()=>{dirty=true;if(id==='target')updateSymbol()});
$('refreshTargets').onclick=()=>act(async()=>{await refreshTargets();await refreshPresets()});$('save').onclick=()=>act(async()=>{await save();toast('配置已保存，下一轮生效')});$('run').onclick=()=>act(async()=>{await save();await api('start',{module:'all'});updateState(await api('state'))});$('single').onclick=()=>act(async()=>{await save();await api('start',{module:modules[selected].id});updateState(await api('state'))});$('stop').onclick=()=>act(async()=>updateState(await api('stop',{})));$('mode').onchange=()=>act(async()=>{const enabled=$('mode').value==='auto';if(enabled)await save();dirty=false;updateState(await api('auto',{enabled}))});$('every').onchange=()=>{dirty=true};
async function init(){modules=await (await fetch('/analysis-catalog.json')).json();state=await api('state');navigate(0);await refreshPresets();applyConfig();updateState(state);refreshTargets().catch(e=>{$('connection').textContent='TradingView未连接';$('target').innerHTML='<option value="">未连接</option>';toast(e.message)});const stream=new EventSource('/api/stream');stream.addEventListener('analysis',e=>updateState(JSON.parse(e.data)));stream.addEventListener('analysis_log',e=>{const d=JSON.parse(e.data);if(d.jobId===state.job?.id){state.job.logs=(state.job.logs||[]).concat(d.message).slice(-120);$('log').textContent=state.job.logs.join('\n')}});stream.onerror=()=>{$('webConnection').textContent='事件连接中断，正在重连'};stream.onopen=()=>{$('webConnection').textContent='WEB服务已连接'};setInterval(()=>act(async()=>updateState(await api('state'))),10000)}
act(init);
