/* SR calibration UI. Uses the regular page's cfg/presets/compute pipeline. */
(() => {
'use strict';
const $ = id => document.getElementById(id);
const root = $('tune-root');
const labels = {W:'周线',D:'日线','240':'4 小时','60':'1 小时','15':'15 分钟','3':'3 分钟'};
const keys = ['minTouch','clusterAtr','recentClusterAtr','recentBiCount'];
const names = ['minTouch · 触及 ≥','flip · 容差 × ATR','recent · 容差 × ATR','recent · 最近笔数'];
let period='60', samples=[], selected=null, preview=null, job=null, capture=null, dirty=false, loading=false, view='after', localStale=false, pageActive=false, applied=false, polling=false;
let baselineSnap=null, lastSymbol=collectCfg().symbol, requestEpoch=0, lastJobStatus='';
const esc = s => String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n = x => x==null?'—':Number(x).toLocaleString('en-US',{maximumFractionDigits:6});
const pct = x => x==null?'—':Math.round(x*100)+'%';
const date = t => t?new Date(t*1000+8*3600000).toISOString().slice(0,16).replace('T',' '):'—';
const now = () => new Date(Date.now()+8*3600000).toISOString().slice(0,16);
const list = () => samples.filter(s=>s.period===period).sort((a,b)=>b.snapshot.cutoff-a.snapshot.cutoff);
const activeSamples = () => list().filter(s=>s.enabled);
const running = () => [job,capture].some(j=>j&&['running','stopping'].includes(j.status));
const occupied = () => loading||running()||!!state.busy||!!state.active;
function message(text,error=false){$('tune-message').textContent=text;$('tune-message').className=error?'tune-error':'tune-note';}
async function request(path,body,method='POST'){
  const r=await fetch('/api/sr/tune/'+path,{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});
  const data=await r.json();if(!r.ok||data.ok===false)throw Error(data.error||'请求失败');return data;
}
function cfgKey(){const c=collectCfg();return JSON.stringify({symbol:c.symbol,from:c.from,period,
  minTouch:c.minTouchs[period],params:c.clusterParamsByPeriod[period],global:[c.clusterAtr,c.recentClusterAtr,c.recentBiCount],
  srTypes:c.srTypes,parts:c.clusterParts,cap:c.maxPerPeriod,weights:[c.touchWeight,c.barsWeight],merge:c.mergeAtr,
  distance:c.maxDistAtr,side:c.sideCount,fib:c.fibLevels,boll:[c.bollLength,c.bollMult],ranges:ranges()});}
root.innerHTML=`
 <div class="tune-intro"><h2><span id="tune-workspace-period"></span> · 自动校准密集区</h2><p>周期跟随左侧选择 · 联合拟合全部启用样本，应用后统一回填左侧参数。</p></div>
 <section class="tune-panel"><div class="tune-head"><h2><span class="tune-step">01</span>人工样本</h2><span class="small muted" id="tune-summary"></span></div>
 <div class="tune-samples"><div class="tune-list" id="tune-list"></div><div class="tune-editor">
 <div class="tune-row tune-spread"><h3 id="tune-editor-title">新建行情快照</h3><span class="tune-pill">仅已收盘 K 线</span></div>
 <div class="tune-fields"><label>截止时刻 · 上海时间<input type="datetime-local" id="tune-cutoff"></label><label>快照方式<select id="tune-mode"><option value="history">指定历史时刻</option><option value="current">保存当前快照</option></select></label><label>允许误差 ±<input id="tune-tolerance" type="number" min="0.000001" step="any"></label></div>
 <div class="tune-row"><button id="tune-capture">读取行情并预览</button><label class="small muted"><input type="checkbox" id="tune-refresh"> 强制刷新行情</label></div>
 <div id="tune-snapshot-meta" class="tune-note">先读取快照，核对实际时间范围，再录入价位。</div>
 <label id="tune-partial" hidden><input type="checkbox" id="tune-accept">起始历史覆盖不足；我已核对并使用所示实际范围。</label>
 <details id="tune-preview-details" hidden><summary class="tune-note">当前参数的截断前候选</summary><div class="tune-preview" id="tune-preview"></div></details>
 <label class="tune-field" style="margin-top:12px">有效密集区价位<textarea id="tune-prices" placeholder="每行一个价位，也可使用逗号分隔"></textarea></label>
 <div class="tune-row tune-spread tune-note"><span>人工列表为已确认的部分，未列出的价位不直接判错</span><span id="tune-price-count">0 个价位</span></div>
 <div class="tune-row tune-spread tune-save"><span class="tune-note" id="tune-save-note"></span><div class="tune-row"><button id="tune-delete" class="danger" hidden>删除样本</button><button id="tune-save">保存样本</button></div></div>
 </div></div></section>
 <section class="tune-search"><div class="tune-row tune-spread"><div><h3><span class="tune-step">02</span>联合拟合本周期全部启用样本</h3><p class="tune-note">样本等权 · 兼顾最差样本 · 一对一价位匹配</p></div><div class="tune-row"><button id="tune-stop" hidden>停止搜索</button><button id="tune-start" class="primary">开始优化 →</button></div></div>
 <div class="tune-progress" id="tune-progress" role="progressbar" aria-label="调参进度" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div id="tune-progress-fill"></div></div><div class="tune-row tune-spread tune-note"><span id="tune-progress-text">等待样本</span><span id="tune-evaluations"></span></div>
 <details class="tune-settings"><summary>高级搜索设置 · 允许尝试的参数范围</summary><div class="tune-ranges" id="tune-ranges"></div><label class="tune-field" style="margin-top:12px">搜索预算<select id="tune-budget"><option value="300">5 分钟 · 深入搜索</option><option value="60">1 分钟 · 快速探索</option></select></label><p class="tune-note">以下为搜索上下限；当前计算参数见左侧。只搜索已开启的 flip / recent。当前参数始终参与比较；继续搜索保留已找到的最佳组合。</p></details></section>
 <div id="tune-message" class="tune-note" role="status" aria-live="polite"></div>
 <div id="tune-stale" class="tune-stale" hidden>样本、参数或搜索范围已变更，请重新优化后再应用。</div>
 <section class="tune-panel" id="tune-report" hidden><div class="tune-head"><h2><span class="tune-step">03</span>优化结果 <span class="tune-pill" id="tune-result-state"></span></h2><span id="tune-result-period" class="small muted"></span></div><div class="tune-metrics" id="tune-metrics"></div><div class="tune-report-body"><h3>建议参数</h3><div id="tune-params" class="tune-params"></div>
 <div class="tune-row tune-spread"><h3>当前样本的价位匹配</h3><div class="tune-row"><button class="small" id="tune-before">优化前</button><button class="small" id="tune-after">优化后</button></div></div>
 <div class="tune-table"><table><thead><tr><th>人工价位</th><th>优化前</th><th>优化后</th><th>价差</th><th>来源</th><th>匹配 / 截断</th></tr></thead><tbody id="tune-matches"></tbody></table></div>
 <div class="tune-chart"><div class="tune-note">价差对齐预览 · 每行中心为人工价位，阴影为允许误差</div><div id="tune-chart-rows"></div><div class="tune-axes" id="tune-chart-axes"></div></div>
 <h3 style="margin-top:20px">全部历史样本的表现</h3><div class="tune-table"><table><thead><tr><th>截止时刻</th><th>目标数</th><th>原匹配率</th><th>新匹配率</th><th>变化</th></tr></thead><tbody id="tune-history"></tbody></table></div>
 <p class="tune-note">评分针对截断前的本周期密集区。表中单独显示候选截断影响；跨周期合并和最终绘图结果请在应用重算后查看“通用计算设置”。这是标注拟合效果，不是收益回测。</p></div>
 <div class="tune-footer"><div><h3 id="tune-apply-state">结果尚未应用</h3><p class="tune-note">只更新本周期的识别参数，应用后重算。</p></div><div class="tune-row"><button id="tune-resume">继续优化</button><button class="primary" id="tune-apply">应用到当前周期</button></div></div></section>
 <dialog class="tune-dialog" id="tune-dialog"><h2>应用建议参数</h2><p id="tune-dialog-sub" class="tune-note"></p><div id="tune-dialog-params" class="tune-params"></div><p class="tune-note">应用后回填参数并执行正常重算。绘图仍由你点击“画图”执行。</p><div class="tune-row" style="margin-top:18px"><button id="tune-cancel-apply">取消</button><button class="primary" id="tune-confirm-apply">应用并重算</button></div></dialog>`;
const box=document.createElement('section');box.id='tune-period-box';box.innerHTML=`<div class="tune-edit-heading">正在编辑 <strong id="tune-period-label"></strong></div><p class="tune-note" id="tune-inherit-note"></p>${keys.map((k,i)=>`<div class="row"><label for="tune-param-${k}">${names[i]}</label><input type="number" id="tune-param-${k}" min="${i===1?.01:i===2?.05:1}" step="${i===1||i===2?'any':'1'}" aria-label="本周期 ${names[i]}"></div>`).join('')}`;
$('tbl-levels').after(box);
const defaultRanges=[[1,20],[.01,5],[.05,5],[1,200]];
$('tune-ranges').innerHTML=keys.map((k,i)=>`<label class="tune-field">${names[i]}<div class="tune-row"><input type="number" aria-label="${names[i]}最小值" id="tune-low-${k}" step="${i===1||i===2?.01:1}" value="${defaultRanges[i][0]}"><span>至</span><input type="number" aria-label="${names[i]}最大值" id="tune-high-${k}" step="${i===1||i===2?.01:1}" value="${defaultRanges[i][1]}"></div></label>`).join('');
function ranges(){return Object.fromEntries(keys.map(k=>[k,[Number($('tune-low-'+k).value),Number($('tune-high-'+k).value)]]));}
function fillParams(){const c=collectCfg(),specific=c.clusterParamsByPeriod[period]||{};const values={minTouch:Number(c.minTouchs[period]),clusterAtr:Number(specific.clusterAtr??c.clusterAtr),recentClusterAtr:Number(specific.recentClusterAtr??c.recentClusterAtr),recentBiCount:Number(specific.recentBiCount??c.recentBiCount)};keys.forEach(k=>$('tune-param-'+k).value=values[k]);$('tune-inherit-note').textContent='修改仅影响本周期 · 手动编辑与自动调参共用';$('tune-period-label').textContent=labels[period];$('tune-workspace-period').textContent=labels[period];document.querySelectorAll('.period-edit').forEach(b=>{b.classList.toggle('selected',b.dataset.period===period);b.setAttribute('aria-pressed',String(b.dataset.period===period));});}
function renderList(){$('tune-summary').textContent=`${labels[period]} · ${list().length} 组样本 / ${activeSamples().length} 组启用`;$('tune-list').innerHTML=list().map(s=>`<div class="tune-item ${selected?.id===s.id?'selected':''}"><input type="checkbox" data-enable="${s.id}" aria-label="启用 ${date(s.snapshot.cutoff)} 样本" ${s.enabled?'checked':''} ${occupied()?'disabled':''}><button data-sample="${s.id}" ${occupied()?'disabled':''}>${date(s.snapshot.cutoff)}<small>${s.prices.length} 个价位 · 误差 ±${n(s.tolerance)}</small></button></div>`).join('')+(list().length?'':'<div class="tune-empty">本周期还没有样本。先创建一组行情快照。</div>')+`<button id="tune-add" ${occupied()?'disabled':''} style="width:100%;margin-top:7px">＋ 新增历史 / 当前样本</button>`;}
function renderSnapshot(){const s=selected?.snapshot||preview?.snapshot;$('tune-snapshot-meta').textContent=s?`实际覆盖 ${date(s.actualFrom)} — ${date(s.actualTo)} · ${s.barCount} 根 K 线 / ${s.biCount} 笔 · ATR ${n(s.atr)} · 指纹 ${s.id.slice(0,10)}`:'先读取快照，核对实际时间范围，再录入价位。';$('tune-partial').hidden=!preview?.snapshot.partial||!!selected;$('tune-preview-details').hidden=!preview;$('tune-preview').textContent=preview?preview.candidates.map(c=>`${n(c.price)} (${c.recent?'recent':'flip'} ${c.type})`).join(' · ')||'当前参数未识别出候选':'';$('tune-editor-title').textContent=selected?`${labels[period]} · 人工标注`:'新建行情快照';$('tune-delete').hidden=!selected;}
function fillEditor(){dirty=false;preview=null;$('tune-cutoff').value=selected?date(selected.snapshot.cutoff).replace(' ','T'):now();$('tune-mode').value='history';$('tune-prices').value=selected?selected.prices.join('\n'):'';$('tune-tolerance').value=selected?selected.tolerance:'';$('tune-save-note').textContent=selected?'行情快照固定，编辑价位将更新样本版本':'';$('tune-accept').checked=false;renderSnapshot();countPrices();}
function countPrices(){const words=$('tune-prices').value.trim().split(/[\s,，;；]+/).filter(Boolean);$('tune-price-count').textContent=words.some(w=>!Number.isFinite(Number(w)))?'含无效输入':new Set(words.map(Number)).size+' 个价位';}
function markStale(){localStale=true;applied=false;renderReport();buttons();}
function paramTiles(params,base){return keys.map((k,i)=>`<div class="tune-param"><small>${names[i]}</small><p><span>${n(base[k])} →</span> ${n(params[k])}</p></div>`).join('');}
function renderReport(){const ready=!!job?.best;$('tune-report').hidden=!ready;$('tune-stale').hidden=!localStale||!job;if(!ready)return;const old=job.baseline,best=job.best;$('tune-result-state').textContent=applied?'已应用':localStale?'待重新优化':best.metrics.score<old.metrics.score-1e-12?'本次搜索最佳':'当前参数已是本次最佳';$('tune-result-period').textContent=`${labels[job.period]} · ${best.metrics.sampleCount} 组样本`;
 const met=(label,a,b)=>`<div class="tune-metric"><label>${label}</label><div>${a} → <strong>${b}</strong></div></div>`;$('tune-metrics').innerHTML=met('历史样本平均匹配率',pct(old.metrics.meanMatchRate),pct(best.metrics.meanMatchRate))+met('拟合损失 · 越小越好',old.metrics.score.toFixed(3),best.metrics.score.toFixed(3))+met('最差样本匹配率',pct(old.metrics.worstMatchRate),pct(best.metrics.worstMatchRate));$('tune-params').innerHTML=paramTiles(best.params,old.params);
 const report=best.samples.find(s=>s.sampleId===selected?.id),before=old.samples.find(s=>s.sampleId===selected?.id);const bm=new Map((before?.matches||[]).map(r=>[r.target,r]));$('tune-matches').innerHTML=report?report.matches.map(r=>`<tr><td class="tune-num">${n(r.target)}</td><td class="tune-num muted">${n(bm.get(r.target)?.price)}</td><td class="tune-num">${n(r.price)}</td><td class="tune-num">${n(r.delta)}</td><td>${esc(r.source||'—')} ${esc(r.type||'')}</td><td class="${r.matched?'tune-green':'tune-orange'}">${r.matched?'✓ 容差内':r.price==null?'未找到':'超出容差'}${r.price!=null&&!r.keptAfterCap?' / 被上限截断':''}</td></tr>`).join(''):'<tr><td colspan="6" class="muted">选择参与本次搜索的样本查看详情</td></tr>';
 const chart=(view==='before'?before:report);$('tune-chart-rows').innerHTML=(chart?.matches||[]).map(r=>{const delta=r.price==null?null:r.price-r.target;const pos=delta==null?50:Math.max(0,Math.min(100,50+delta/chart.tolerance*12.5));return `<div class="tune-align"><span>${n(r.target)}</span><div class="tune-track"><div class="tune-band"></div><div class="tune-center"></div>${delta==null?'':`<div class="tune-dot ${view==='before'?'old':''}" style="left:${pos}%"></div>`}</div><span class="${r.matched?'tune-green':'tune-orange'}">${delta==null?'未匹配':(delta>=0?'+':'')+n(delta)}</span></div>`;}).join('');$('tune-chart-axes').innerHTML=chart?`<span>≤ −${n(chart.tolerance*4)}</span><span>价格偏差 0</span><span>≥ +${n(chart.tolerance*4)}</span>`:'';
 $('tune-history').innerHTML=best.samples.map(s=>{const b=old.samples.find(x=>x.sampleId===s.sampleId);const d=Math.round((s.matchRate-b.matchRate)*100);return `<tr><td><button class="tune-link" data-report-sample="${s.sampleId}">${date(s.cutoff)}</button></td><td class="tune-num">${s.targetCount}</td><td class="tune-num muted">${pct(b.matchRate)}</td><td class="tune-num">${pct(s.matchRate)}</td><td class="${d<0?'tune-orange':'tune-green'}">${d>0?'+':''}${d} 个百分点</td></tr>`;}).join('');$('tune-apply-state').textContent=applied?'参数已回填，重算中或已完成':'结果尚未应用';}
function buttons(){const busy=occupied();document.querySelectorAll('.period-edit').forEach(b=>b.disabled=busy);$('cfg-symbol').disabled=running();$('cfg-from').disabled=running();const s=selected?.snapshot||preview?.snapshot;for(const id of ['tune-add','tune-delete','tune-mode','tune-prices','tune-tolerance','tune-refresh'])if($(id))$(id).disabled=busy;$('tune-cutoff').disabled=busy||!!selected||$('tune-mode').value==='current';$('tune-mode').disabled=busy||!!selected;$('tune-capture').disabled=busy||!!selected;$('tune-save').disabled=busy||!s;$('tune-start').disabled=busy||dirty||!activeSamples().length;$('tune-stop').hidden=!running();$('tune-stop').disabled=false;$('tune-apply').disabled=busy||dirty||localStale||!job?.best||applied;$('tune-resume').disabled=busy||dirty||localStale||!job||!job.baseline;keys.forEach(k=>{$('tune-param-'+k).disabled=busy;$('tune-low-'+k).disabled=busy;$('tune-high-'+k).disabled=busy;});$('tune-budget').disabled=busy;}
function showProgress(){const j=capture||job;const statuses={running:'运行中',completed:'已完成',stopped:'已停止，可继续',interrupted:'服务已重启，可继续',failed:'失败'};$('tune-progress-text').textContent=j?`${j.kind==='snapshot'?'准备快照':'参数搜索'} · ${statuses[j.status]||j.status}${j.error?' · '+j.error:''}`:'保存并启用样本后即可开始搜索';$('tune-evaluations').textContent=j?.kind==='search'?`${j.evaluations||0} 组参数 · 累计 ${Math.round(j.elapsedSeconds||0)} 秒`:'';const progress=j?.kind==='snapshot'?(j.status==='completed'?100:10):(j?.progress||0);$('tune-progress-fill').style.width=progress+'%';$('tune-progress').setAttribute('aria-valuenow',progress);}
async function load(){const epoch=++requestEpoch,symbol=collectCfg().symbol.toUpperCase();lastSymbol=collectCfg().symbol;try{const [ss,jj]=await Promise.all([request('samples?symbol='+encodeURIComponent(symbol),null,'GET'),request('jobs?symbol='+encodeURIComponent(symbol)+'&period='+period,null,'GET')]);if(epoch!==requestEpoch)return;samples=ss.samples;selected=list().find(s=>s.id===selected?.id)||list()[0]||null;job=jj.jobs.find(j=>j.kind==='search')||null;capture=jj.jobs.find(j=>j.kind==='snapshot'&&['running','stopping'].includes(j.status))||null;localStale=!!job&&Object.entries(job.sampleVersions||{}).some(([id,v])=>!samples.some(s=>s.id===id&&s.version===v&&s.enabled));if(job&&activeSamples().length!==Object.keys(job.sampleVersions||{}).length)localStale=true;if(job){const valid=await request('jobs/'+job.id+'/validate',{cfg:collectCfg()});if(epoch!==requestEpoch)return;localStale=localStale||!valid.compatible;Object.entries(job.ranges).forEach(([k,b])=>{$('tune-low-'+k).value=b[0];$('tune-high-'+k).value=b[1];});}baselineSnap=job?cfgKey():null;applied=false;fillEditor();fillParams();renderList();renderReport();showProgress();buttons();}catch(e){message(e.message,true);}}
async function guard(fn){if(loading)return;loading=true;buttons();try{await fn();}catch(e){message(e.message,true);}finally{loading=false;await refreshState();buttons();renderList();}}
function choose(id){if(dirty){message('请先保存当前编辑，或点击新增样本放弃未保存内容。',true);return;}selected=samples.find(s=>s.id===id)||null;fillEditor();renderList();renderReport();buttons();}
document.querySelectorAll('.period-edit').forEach(b=>b.onclick=()=>{if(occupied()||b.dataset.period===period)return;if(dirty){message('请先保存样本再切换周期。',true);return;}period=b.dataset.period;selected=null;preview=null;job=null;capture=null;fillParams();fillEditor();renderList();renderReport();showProgress();guard(load);});
$('tune-auto-tab').onclick=()=>{if(pageActive)return;pageActive=true;root.hidden=false;$('sr-manual').hidden=true;$('tune-auto-tab').classList.add('selected');$('tune-manual-tab').classList.remove('selected');if(!samples.length&&!job&&!preview)guard(load);else buttons();};
$('tune-manual-tab').onclick=()=>{pageActive=false;root.hidden=true;$('sr-manual').hidden=false;$('tune-manual-tab').classList.add('selected');$('tune-auto-tab').classList.remove('selected');};
keys.forEach(k=>$('tune-param-'+k).onchange=()=>{const v=Number($('tune-param-'+k).value);if(!Number.isFinite(v)||v<=0||(['minTouch','recentBiCount'].includes(k)&&!Number.isInteger(v))){message('参数必须为正数，触及次数和笔数必须为整数。',true);fillParams();return;}if(k==='minTouch')minTouchsByPeriod[period]=v;else{clusterParamsByPeriod[period]??={};clusterParamsByPeriod[period][k]=v;}fillParams();markStale();checkStale();updateButtons();});
// Commit valid edits immediately so switching focus/period cannot discard them.
keys.forEach(k=>$('tune-param-'+k).addEventListener('input',()=>{const v=Number($('tune-param-'+k).value);if(!Number.isFinite(v)||v<=0||(['minTouch','recentBiCount'].includes(k)&&!Number.isInteger(v)))return;if(k==='minTouch')minTouchsByPeriod[period]=v;else{clusterParamsByPeriod[period]??={};clusterParamsByPeriod[period][k]=v;}markStale();checkStale();updateButtons();}));
$('tune-list').onclick=e=>{const b=e.target.closest('[data-sample]');if(b)choose(b.dataset.sample);if(e.target.id==='tune-add'){selected=null;preview=null;fillEditor();renderList();buttons();}};
$('tune-list').onchange=e=>{if(!e.target.dataset.enable)return;const s=samples.find(s=>s.id===e.target.dataset.enable);guard(async()=>{const r=await request('samples',{id:s.id,version:s.version,enabled:e.target.checked});samples=samples.map(x=>x.id===s.id?r.sample:x);if(selected?.id===s.id)selected=r.sample;markStale();});};
['tune-prices','tune-tolerance'].forEach(id=>$(id).addEventListener('input',()=>{dirty=true;$('tune-save-note').textContent='有未保存修改';countPrices();buttons();}));
$('tune-cutoff').onchange=()=>{preview=null;renderSnapshot();buttons();};
$('tune-mode').onchange=()=>{if($('tune-mode').value==='current')$('tune-cutoff').value=now();preview=null;renderSnapshot();buttons();};
$('tune-capture').onclick=()=>guard(async()=>{if($('tune-mode').value==='current')$('tune-cutoff').value=now();const r=await request('snapshots',{cfg:collectCfg(),period,cutoff:$('tune-cutoff').value,refresh:$('tune-refresh').checked});capture=r.job;preview=null;message('正在读取该品种与周期的行情，首次拉取可能需要几分钟。');showProgress();});
$('tune-save').onclick=()=>guard(async()=>{const body={prices:$('tune-prices').value,tolerance:$('tune-tolerance').value};if(selected)Object.assign(body,{id:selected.id,version:selected.version});else Object.assign(body,{snapshotId:preview?.snapshot.id,acceptPartial:$('tune-accept').checked});const r=await request('samples',body);samples=[r.sample,...samples.filter(s=>s.id!==r.sample.id)];selected=r.sample;fillEditor();markStale();message('样本已保存，后续搜索会同时评价全部启用样本。');});
$('tune-delete').onclick=()=>guard(async()=>{await request('samples/'+selected.id+'?version='+selected.version,null,'DELETE');samples=samples.filter(s=>s.id!==selected.id);selected=list()[0]||null;fillEditor();markStale();message('样本已移出拟合列表。');});
async function search(resume){const c=collectCfg();if(!c.srTypes.includes('cluster')||!c.clusterParts.length)throw Error('请在左侧开启密集区及至少一种子类型。');if(!c.periods.includes(period)){document.querySelector(`#tbl-levels tr[data-res="${period}"] .chk-res`).checked=true;}const r=await request(resume?'jobs/'+job.id+'/resume':'jobs',{cfg:collectCfg(),period,budgetSeconds:Number($('tune-budget').value),ranges:ranges()});job=r.job;capture=null;baselineSnap=cfgKey();localStale=false;applied=false;lastJobStatus='';message('搜索使用固定历史快照，不随实时行情变化。');renderReport();showProgress();}
$('tune-start').onclick=()=>guard(()=>search(false));$('tune-resume').onclick=()=>guard(()=>search(true));
$('tune-stop').onclick=()=>guard(async()=>{const j=capture||job;await request('jobs/'+j.id+'/stop',{});message('停止请求已发送，正在保存本次最佳结果。');});
keys.forEach(k=>['tune-low-','tune-high-'].forEach(prefix=>$(prefix+k).onchange=markStale));
$('tune-before').onclick=()=>{view='before';renderReport();};$('tune-after').onclick=()=>{view='after';renderReport();};
$('tune-history').onclick=e=>{const b=e.target.closest('[data-report-sample]');if(b)choose(b.dataset.reportSample);};
$('tune-apply').onclick=()=>{$('tune-dialog-sub').textContent=`${collectCfg().symbol} / ${labels[period]} / ${job.best.metrics.sampleCount} 组样本`;$('tune-dialog-params').innerHTML=paramTiles(job.best.params,job.baseline.params);$('tune-dialog').showModal();};
$('tune-cancel-apply').onclick=()=>$('tune-dialog').close();
$('tune-confirm-apply').onclick=()=>guard(async()=>{const r=await request('jobs/'+job.id+'/apply',{cfg:collectCfg()});$('tune-dialog').close();applyCfgToUI(r.cfg);applied=true;localStale=false;baselineSnap=null;fillParams();renderReport();await refreshState();await doCompute('auto');message('参数已回填并提交重算；重算完成后可在通用计算设置页画图。');});
window.addEventListener('sr-config-loaded',()=>{fillParams();if(job)markStale();});
async function poll(){if(polling||(!pageActive&&!running()))return;polling=true;try{if(lastSymbol!==collectCfg().symbol){lastSymbol=collectCfg().symbol;selected=null;job=null;capture=null;preview=null;await load();return;}const target=capture||job;if(target&&['running','stopping'].includes(target.status)){const r=await request('jobs/'+target.id,null,'GET');if(target.kind==='snapshot'){capture=r.job;if(capture.status==='completed'){preview=capture.preview;$('tune-tolerance').value=preview.suggestedTolerance;renderSnapshot();message('行情快照已固定，请核对覆盖范围并录入人工价位。');capture=null;await refreshState();}else if(['failed','stopped','interrupted'].includes(capture.status)){message(capture.error||'快照任务已停止',true);capture=null;await refreshState();}}else{job=r.job;if(job.status!==lastJobStatus){lastJobStatus=job.status;if(!['running','stopping'].includes(job.status))await refreshState();}renderReport();}showProgress();renderList();}if(baselineSnap&&cfgKey()!==baselineSnap&&!localStale)markStale();buttons();}catch(e){message(e.message,true);}finally{polling=false;}}
fillParams();fillEditor();renderList();buttons();setInterval(poll,1200);
document.addEventListener('input',e=>{if(!e.target.closest('#tune-root')&&!e.target.closest('#tune-period-box'))fillParams();});
if(new URLSearchParams(location.search).get('tab')==='auto')$('tune-auto-tab').click();
})();
